<a href="https://colab.research.google.com/github/harshithareddy888/PythonLibrariesPractice/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#initialising an array
a=np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [ ]:
#2-d array
b=np.array([[9,0,8,0],[6,0,4,0]])
print(b)

[[9 0 8 0]
 [6 0 4 0]]


In [ ]:
#get the dimension of the array
a.ndim #1
b.ndim #2

2

In [ ]:
#get shape
a.shape #(3,)
b.shape #(2,4)

(2, 4)

In [ ]:
#get type - you specify the data type while creating the array
a.dtype #if we don't specify its 'int64' but since we specified its 'int16'

dtype('int16')

In [ ]:
#get size - gives us the numb of bytes
a.itemsize #2 since the dtype is specified to int16, if we change the dtype value byte size also varies

#get total size
a.size #total no of elements
a.size * a.itemsize #total size
a.nbytes #another way to get total size

6

In [ ]:
#access/changing specific elements rows and columns
c=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#get specific element
#c[row,col]
c[1,5]

#get a specific column
c[0,:]

#get a specific column
c[:,2]

array([ 3, 10])

In [ ]:
#[startindex:endindex:stepsize]
c[0,1:6:2]

array([2, 4, 6])

In [ ]:
#change a specific value
c[1,5]=20
print(c)

c[:,2]=5
print(c)
#if two numbers needs to be modified
c[:,2]=[1,2]
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
#3-d example
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#get specific element
d[:,1,:]

array([[3, 4],
       [7, 8]])

In [ ]:
#replace - as long its of same dimension it'll work
d[:,1,:]=[[9,9],[8,8]]
print(d)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [ ]:
#initalising diff types of arrays

#all 0's matrix
np.zeros((2,3)) #2 rows and 3 columns

#all 1's matrix
np.ones((4,2,2),dtype='int32') #4 rows and 2 columns

#any other number
np.full((2,2),99) #2x2 matrix with value 99

array([[99, 99],
       [99, 99]])

In [ ]:
#any other number(full_like)
np.full_like(c,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
#random decimal numbers
np.random.rand(4,2,3)  #3-dimensional array with 4 "layers", each containing a 2x3 matrix.

array([[[0.04030272, 0.53775485, 0.42294438],
        [0.97825738, 0.85321995, 0.51438615]],

       [[0.63482521, 0.49742368, 0.52629693],
        [0.76392826, 0.5555881 , 0.81064493]],

       [[0.58952684, 0.66752875, 0.43706766],
        [0.30939749, 0.30020979, 0.20582308]],

       [[0.49139181, 0.35794385, 0.94432071],
        [0.75215775, 0.85354925, 0.20431254]]])

In [ ]:
np.random.random_sample(c.shape)

array([[0.45958439, 0.23554794, 0.29371958, 0.32825792, 0.35948671,
        0.2169464 , 0.75297483],
       [0.65007099, 0.78118453, 0.28333743, 0.8053986 , 0.14242717,
        0.25556281, 0.29961642]])

In [ ]:
#random Integer values
np.random.randint(4,7, size=(3,3)) #7- start value, if not specified it assumes the values as 0 and if size is specified its just gonna do one number
#here the range of the random numbers are 4-7 but it doesn't include 7 (like for loops in python) if you want the range till n num, you should specify n+1

array([[6, 4, 6],
       [4, 5, 6],
       [4, 6, 6]])

In [ ]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#repeat an array
#1-d
arr=np.array([1,2,3])
r1=np.repeat(arr,3,axis=0)
print(r1) #o/p [1 1 1 2 2 2 3 3 3]

#2-d
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
output=np.ones((5,5))
# print(output)

z=np.zeros((3,3))
z[1,1]=9
# print(z)

output[1:4,1:4]=z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# be careful when copying arrays
a=np.array([1,2,3])
# b=a
b[0]=100

#to prevent that
b=a.copy()
print(a)


[1 2 3]


In [ ]:
#addition
a+2

array([3, 4, 5])

In [ ]:
#subtraction
a-2

array([-1,  0,  1])

In [ ]:
#multiply
a*2

array([2, 4, 6])

In [ ]:
#division
a/2

array([0.5, 1. , 1.5])

In [ ]:
e=np.array([1,0,1]) # Changed shape to match 'a'
a+e

array([2, 2, 4])

In [ ]:
a**2  #square

array([1, 4, 9])

In [ ]:
#sin of the values
np.sin(a)

#cos of the values
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [ ]:
#linear algebra
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)

# a*b (this won't work bcoz of diff dimensions)

#numpy has matrix mul function
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
#to find the determinant
c=np.identity(3)
np.linalg.det(c)

#numpy can help us find determinant, trace, singular vector decomposition, eigen values, matrix norms, inverse etc...

np.float64(1.0)

In [ ]:
#statistics
stats=np.array([[1,2,3],[4,5,6]])
stats

np.min(stats) #1

np.max(stats, axis=1) #array([3,6])
np.sum(stats, axis=0) #array([5, 7, 9])

array([5, 7, 9])

In [ ]:
#reorganizing arrays
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape((2,2,2)) #reshaoes the array structure
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
#horizontal stack
h1=np.ones((2,4))
h2=np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [ ]:
#load data from file
filedata=np.genfromtxt('filelocation.txt',delimiter=',')
filedata=filedata.astype('int32') #to change the data type
filedata

filedata >50 #this return true for the values greater than 50 or else false

filedata[filedata>50] #return the values itself which are greater than 50

np.any(filedata > 50, axis=1) #to check the values in any column is greater than 50

((filedata>50) & (filedata<100)) #return in form of T & F


FileNotFoundError: filelocation.txt not found.

In [ ]:
#you can index with yiur list in numpy
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])